# Generated by Django 3.1.5 on 2021-11-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Family',
        ),
    ]
