# Generated by Django 3.1.5 on 2021-12-07 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211206_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='allergy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='family',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='isVeggie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='toCeremony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='toDiner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='toParty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='toReception',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
