# Generated by Django 3.1.5 on 2021-12-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211207_2133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='FamilyMember',
        ),
    ]
