# Generated by Django 3.1.5 on 2021-12-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211208_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='allergy',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
