# Generated by Django 3.1.5 on 2021-12-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211208_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='toDinner',
            field=models.BooleanField(blank=True, default=False, verbose_name='Dinner'),
        ),
    ]
