# Generated by Django 3.1.5 on 2021-12-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20211211_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='allergy',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Allergies'),
        ),
    ]
