# Generated by Django 3.1.5 on 2021-12-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211212_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='isVeggie',
        ),
        migrations.AddField(
            model_name='familymember',
            name='specialRequest',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Special Request'),
        ),
    ]
