# Generated by Django 3.1.5 on 2021-12-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211212_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='specialRequest',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Remark'),
        ),
    ]
