# Generated by Django 3.1.5 on 2022-01-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20211214_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='address',
        ),
        migrations.RemoveField(
            model_name='family',
            name='language',
        ),
        migrations.AlterField(
            model_name='familymember',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='toCeremony',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='toDinner',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='toParty',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='toReception',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
