# Generated by Django 3.1.5 on 2022-01-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20220105_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_date',
        ),
    ]
