# Generated by Django 3.1.5 on 2022-01-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20220105_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_due_date',
            field=models.DateField(null=True),
        ),
    ]
