# Generated by Django 3.1.5 on 2021-09-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pater', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('ceremony', models.BooleanField()),
                ('reception', models.BooleanField()),
                ('diner', models.BooleanField()),
                ('party', models.BooleanField()),
                ('veggie', models.BooleanField()),
                ('allergy', models.BooleanField()),
                ('isPlusOne', models.BooleanField()),
                ('present', models.BooleanField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.family')),
            ],
        ),
    ]
