# Generated by Django 3.1.5 on 2021-09-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210923_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='allergy',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
