# Generated by Django 3.1.5 on 2021-09-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_invitee_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
