# Generated by Django 3.1.5 on 2021-09-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_invitee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='Language',
            field=models.CharField(choices=[('XX', '?'), ('NL', 'Nederlands'), ('FR', 'Français')], default='?', max_length=200),
        ),
    ]
