# Generated by Django 3.1.5 on 2021-09-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_auto_20210926_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='pater',
            new_name='head',
        ),
    ]
