# Generated by Django 3.1.5 on 2021-11-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_auto_20210927_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
