# Generated by Django 3.1.5 on 2021-11-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_auto_20211101_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitee',
            old_name='Language',
            new_name='language',
        ),
    ]
