# Generated by Django 3.1.5 on 2022-01-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='image_location',
            field=models.CharField(default='products/Heenreis.jpg', max_length=50),
        ),
    ]
