# Generated by Django 3.1.5 on 2022-01-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220102_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_location',
        ),
        migrations.AddField(
            model_name='product',
            name='description_FR',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='name_FR',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='Heenreis_L9ruoMo.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
