# Generated by Django 3.1.5 on 2022-01-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220102_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='static/products/Heenreis.jpg', upload_to='static/products/'),
        ),
    ]
