# Generated by Django 3.1.5 on 2022-01-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220103_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product',
            name='img_path',
            field=models.CharField(default='', max_length=50),
        ),
    ]
