# Generated by Django 3.1.5 on 2022-01-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220103_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_path',
            new_name='img_name',
        ),
    ]
