# Generated by Django 3.1.5 on 2022-01-03 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220103_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_name',
            new_name='image_path',
        ),
    ]
